### PR TITLE
Remove hard dependency on `capistrano/rails`

### PR DESCRIPTION
**Pull request by dadooda**
Hey guys,

Our project is an API-only Rails application which doesn't have the assets part, and, therefore doesn't require `capistrano/rails` (which is legal).

Better not do it in the gem as well. The project will handle Capistrano stuff on its own anyway.

The fix implements this approach.

### CODE REVIEW

**Comment by berfarah** [comment]
Hi @dadooda! Thanks for the suggestion! Currently, this PR would break deploying to a server, since we depend on `capistrano/rails` for their `:set_rails_env` task (see [here](https://github.com/coverhound/sidekiq-cron-tasks/blob/master/lib/capistrano/tasks/sidekiq_cron.rake#L6)).

You mentioned that your usecase is a Rails API application. In order to deploy it using Capistrano, what are you using to run migrations if not `capistrano/rails`?

**Comment by dadooda** [comment]
Hey Bernardo,

Here's an extract from my current `Capfile`:

```
require "capistrano/bundler"
require "capistrano/deploy"
require "capistrano/rails/migrations"
require "capistrano/rpush"
require "capistrano/rvm"
require "capistrano/setup"
require "capistrano/sidekiq-cron"
require "capistrano/sidekiq"
require "capistrano3/unicorn"
```

Not requiring `capistrano/rails` for an asset-less project is a legal way. See discussion at: https://stackoverflow.com/questions/41052204/deploy-raise-error-dont-know-how-to-build-task-assetsprecompile-capistran.

Regarding dependency from `:set_rails_env`, my project runs an "operated" version of the gem and the deployment goes smoothly. `capistrano/rails` doesn't get required anywhere at all.

Thank you!

**Comment by berfarah** [comment]
Ah, I see, you're doing a deep require. It happens not to break for you because you are doing `require "capistrano/rails/migrations"` which in turn requires the task we need.

I can see why we would want to not require assets when only migrations are required.

Could you change your PR to, instead of deleting the require line, changing it to require `capistrano/rails/migrations`?

**Comment by dadooda** [comment]
Hey Bernardo,

Changed the require line like you requested.

**Comment by berfarah** [comment]
@strobmax In order to load the `set_rails_env` capistrano task which makes sure tasks are run with the right Rails environment.

There are a few options here:
1. Write our own task that sets the rails environment. The downside here is that we would either not keep compatibility with `capistrano-rails`, or loose compatibility, where we have to know about the variables they're setting to run this task.
2. Reach into `capistrano-rails` and do a deep require of the `set_rails_env` task. This would mean that we have to know about their file system, and I think we'd have to use `Gem` to look up the path of `capistrano-rails`.
3. Depend on `migrations` which includes the `set_rails_env` task.

This gem also currently depends on  `rails` as it calls `Rails.root`.

**Comment by berfarah** [comment]
Actually, I'll just go ahead and merge + release.

**Comment by berfarah** [comment]
Thanks for your contribution! This is now released under `0.3.1`.

**Pull request merged**
